[package]
name = "dirble"
version = "0.1.0"
authors = ["Izzy Whistlecroft <izzy.whistlecroft@nccgroup.com>"]
edition = "2018"

[dependencies]
curl = "0.4.19"
percent-encoding = "1.0.1"
clap = {version = "2.32", features = ["yaml"]}